# -*- coding: utf-8 -*-
"""FINALBME450CODE with ALL ALTERNATIVES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18I-eikEjpkklmLfblefGCIQditoHipLv

This first section includes all the code necessary for data processing before the neural networks are used.
"""

# importing all the necessary libraries and google drive (where sound files are located)
from google.colab import drive
drive.mount('/content/drive')

!pip install pydub librosa matplotlib
!apt-get update && !apt-get install -y ffmpeg

!pip install noisereduce

import os
import glob
from pydub import AudioSegment
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np

# defining where the bird calls are located
base_drive_path = '/content/drive/My Drive/BirdCalls'

# Defining each bird call locations in the drive
bird_species_folders = ['barredowl', 'americanbarnowl', 'greathornedowl']

# instead of outputing right in the code, the wav files and spectrograms will
# be saved in folders in the drive
Create output directories
output_wav_dir = os.path.join(base_drive_path, 'converted_wavs')
output_spectrogram_dir = os.path.join(base_drive_path, 'spectrograms')

os.makedirs(output_wav_dir, exist_ok=True)
os.makedirs(output_spectrogram_dir, exist_ok=True)

# creating a function where the mp3 files of the bird calls will be converted
# into WAV files. If the file is already a wav file, then it will not be
# converted. It will also output to the user if the files were actually converted
# or not and it shows where they are located in the drive
def convert_to_wav(input_folder, output_folder):
    """Converts all audio files in a folder to WAV format."""
    print(f"Converting files in {input_folder} to WAV...")
    converted_files = []
    for filepath in glob.glob(os.path.join(input_folder, '*.*')):
        filename = os.path.basename(filepath)
        name, ext = os.path.splitext(filename)

        # if already wav file and in folder, not need to convert
        if ext.lower() == '.wav':
            output_filepath = os.path.join(output_folder, filename)
            if not os.path.exists(output_filepath):
                # If it's a WAV but not in the output folder, it is copied
                import shutil
                shutil.copy(filepath, output_filepath)
            converted_files.append(output_filepath)
            continue

        try:
            audio = AudioSegment.from_file(filepath)
            output_filepath = os.path.join(output_folder, name + '.wav')
            audio.export(output_filepath, format='wav')
            converted_files.append(output_filepath)
            print(f"  Converted {filename} to {os.path.basename(output_filepath)}")
        except Exception as e:
            print(f"  Error converting {filename}: {e}")
    print(f"Finished WAV conversion for {input_folder}. Total converted: {len(converted_files)}\n")
    return converted_files

# creating the function that creates spectrograms of the wav files
# creates a folder for the spectrograms that are created
def generate_spectrogram(wav_filepath, output_folder):
    """Generates and saves a spectrogram for a given WAV file."""
    filename = os.path.basename(wav_filepath)
    name, _ = os.path.splitext(filename)
    output_spectrogram_filepath = os.path.join(output_folder, name + '.png')


    if os.path.exists(output_spectrogram_filepath):
        # if there is already a spectrogram, it is not recreated
        return
# this is where the actual spectrograms are created using librosa libraries and
# matplotlib libraries. Additionally, it there is an error in creation of spectrograms,
# the user is informed
    try:
        y, sr = librosa.load(wav_filepath)
        D = librosa.amplitude_to_db(np.abs(librosa.stft(y)), ref=np.max)

        plt.figure(figsize=(10, 4))
        librosa.display.specshow(D, sr=sr, x_axis='time', y_axis='log')
        plt.colorbar(format='%+2.0f dB')
        plt.title(f'Spectrogram of {name}')
        plt.tight_layout()
        plt.savefig(output_spectrogram_filepath)
        plt.close()
        print(f"  Generated spectrogram for {filename}")
    except Exception as e:
        print(f"  Error generating spectrogram for {filename}: {e}")

# this fucntion actually creates the wav files and spectrograms by using the previously
# defined functions for doing so. There are already output folders for spectrograms and
# wav files, but this also creates a subfolder for each species
def process_bird_folder(bird_folder_name):
    """Processes a single bird species folder: converts to WAV and generates spectrograms."""
    input_folder = os.path.join(base_drive_path, bird_folder_name)

    # Creating species wav subfolder
    species_wav_output_folder = os.path.join(output_wav_dir, bird_folder_name)
    os.makedirs(species_wav_output_folder, exist_ok=True)

    # Creating species spectrogram subfolder
    species_spectrogram_output_folder = os.path.join(output_spectrogram_dir, bird_folder_name)
    os.makedirs(species_spectrogram_output_folder, exist_ok=True)

    # actual conversion of mp3 audio to wav files
    wav_files = convert_to_wav(input_folder, species_wav_output_folder)

    # actual creation of spectrograms
    print(f"Generating spectrograms for WAV files in {species_wav_output_folder}...")
    for wav_file in wav_files:
        generate_spectrogram(wav_file, species_spectrogram_output_folder)
    print(f"Finished spectrogram generation for {bird_folder_name}.\n")


# importing noisereduce as this helps eliminate background noise
import noisereduce as nr
import soundfile as sf # helps in writing audio files

# a new folder is needed for the noise-reduced wav files
output_noise_reduced_wav_dir = os.path.join(base_drive_path, 'noise_reduced_wavs')
os.makedirs(output_noise_reduced_wav_dir, exist_ok=True)

# this function is creating the noise reduction process that will be used and it makes
# sure that a folder is created
def apply_noise_reduction(wav_filepath, output_folder):
    """Applies noise reduction to a WAV file and saves it."""
    filename = os.path.basename(wav_filepath)
    name, ext = os.path.splitext(filename)
    output_filepath = os.path.join(output_folder, name + '_nr' + ext)

    if os.path.exists(output_filepath):
        # additionally, if there is already a noise-reduced wav file, it does not make a new one
        return output_filepath

# this is where the noise reduction library is used to perform the reduction
    try:
        y, sr = librosa.load(wav_filepath, sr=None)
        reduced_noise_audio = nr.reduce_noise(y=y, sr=sr, stationary=True)

        # this helps save the noise-reduced wav as an audio file and if there is an
        # error the user is informed
        sf.write(output_filepath, reduced_noise_audio, sr)
        print(f"  Applied noise reduction to {filename}")
        return output_filepath
    except Exception as e:
        print(f"  Error applying noise reduction to {filename}: {e}")
        return None

# this function applies the other function to actually create noise-reduced wavs and spectrograms
def process_bird_folder_with_noise_reduction(bird_folder_name):
    """Processes a single bird species folder: converts to WAV, applies noise reduction, and generates spectrograms."""
    input_folder = os.path.join(base_drive_path, bird_folder_name)

    # Creating a species subfolder for wavs
    species_wav_output_folder = os.path.join(output_wav_dir, bird_folder_name)
    os.makedirs(species_wav_output_folder, exist_ok=True)

    # converting to wav files
    print(f"Processing {bird_folder_name}:")
    converted_wav_files = convert_to_wav(input_folder, species_wav_output_folder)

    # Creating a species subfolder for noise-reduced wavs
    species_noise_reduced_output_folder = os.path.join(output_noise_reduced_wav_dir, bird_folder_name)
    os.makedirs(species_noise_reduced_output_folder, exist_ok=True)

    # actually applying the noise reduction for the wav files using previously defined functions
    print(f"Applying noise reduction for WAV files in {species_wav_output_folder}...")
    noise_reduced_files = []
    for wav_file in converted_wav_files:
        reduced_file = apply_noise_reduction(wav_file, species_noise_reduced_output_folder)
        if reduced_file:
            noise_reduced_files.append(reduced_file)
    print(f"Finished noise reduction for {bird_folder_name}. Total reduced: {len(noise_reduced_files)}\n")

    # Creating species subfolder for noise-reduced spectrograms
    species_spectrogram_output_folder = os.path.join(output_spectrogram_dir, bird_folder_name)
    os.makedirs(species_spectrogram_output_folder, exist_ok=True)

    # creating noise-reduced spectrograms
    print(f"Generating spectrograms for noise-reduced WAV files in {species_noise_reduced_output_folder}...")
    for nr_file in noise_reduced_files:
        generate_spectrogram(nr_file, species_spectrogram_output_folder)
    print(f"Finished spectrogram generation for {bird_folder_name}.\n")

# this is now using the defined functions to create wav files and spectrograms and this
# is done for each species in a loop and for both noise-reduction and original
for folder_name in bird_species_folders:
    process_bird_folder_with_noise_reduction(folder_name)

print("All bird call files processed with noise reduction!")
print(f"Converted WAV files are saved in: {output_wav_dir}")
print(f"Noise-reduced WAV files are saved in: {output_noise_reduced_wav_dir}")
print(f"Spectrograms are saved in: {output_spectrogram_dir}")


for folder_name in bird_species_folders:
    process_bird_folder(folder_name)

print("All bird call files processed!")
print(f"Converted WAV files are saved in: {output_wav_dir}")
print(f"Spectrograms are saved in: {output_spectrogram_dir}")


# importing necessary libraries
import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np
import os
import glob

# Defining the spectrogram dimensions
IMG_HEIGHT = 128 # Number of frequency bins (rows)
IMG_WIDTH = 128  # Number of time steps (columns)

# all the previous paths
base_drive_path = '/content/drive/My Drive/BirdCalls'
output_spectrogram_dir = os.path.join(base_drive_path, 'spectrograms')
bird_species_folders = ['barredowl', 'americanbarnowl', 'greathornedowl']


# initializing data and labels lists
data = []
labels = []

# using a loop to go through the three bird species and performing the following:
# making sure there is a folder containing the spectrograms and telling user if there is not
# making sure the actual spectrogram images exist and telling user if it does not
# then it contains another for loop where the spectrograms are set to specific dimensions defined previously
# and it converts them to greyscale. It also normalizes the data from 0 to 1.
# then the data is added to the lists
for i, species in enumerate(bird_species_folders):
    species_spectrogram_folder = os.path.join(output_spectrogram_dir, species)

    if not os.path.exists(species_spectrogram_folder):
        print(f"Warning: Species spectrogram folder does not exist: {species_spectrogram_folder}. Skipping.")
        continue

    print(f"Loading spectrograms for {species} from {species_spectrogram_folder}...")
    image_files = glob.glob(os.path.join(species_spectrogram_folder, '*.png'))
    if not image_files:
        print(f"  No PNG files found in {species_spectrogram_folder}. Skipping.")
        continue

    for img_path in image_files:
        try:
            # Loading images as grayscale
            img = load_img(img_path, color_mode='grayscale', target_size=(IMG_HEIGHT, IMG_WIDTH))
            img_array = img_to_array(img)

            # Normalizing to [0, 1] range
            img_array = img_array / 255.0

            data.append(img_array)
            labels.append(species)
        except Exception as e:
            print(f"Error loading or processing {img_path}: {e}")
# list conversion into arrays
data = np.array(data)
labels = np.array(labels)

# showing users that the data has been processed
print(f"Loaded {len(data)} spectrograms.")
print(f"Data shape: {data.shape}")
print(f"Labels shape: {labels.shape}")


# Re-encoding labels to numerical values
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

# determing how many species there are, so 3 and then converting numerical value to vector
num_classes = len(label_encoder.classes_)
encoded_labels_onehot = tf.keras.utils.to_categorical(encoded_labels, num_classes=num_classes)

# show user that the relabeling has occurred
print(f"Encoded labels (first 5): {encoded_labels[:5]}")
print(f"One-hot encoded labels (first 5): {encoded_labels_onehot[:5]}")
print(f"Classes: {label_encoder.classes_}")

# Spliting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    data, encoded_labels_onehot, test_size=0.2, random_state=42, stratify=encoded_labels
)

print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")


# doing same spectrogram creation for species but with enhanced noise-reduced data to ensure accuracy
data_enhanced = []
labels_enhanced = []

for i, species in enumerate(bird_species_folders):
    species_spectrogram_folder = os.path.join(output_spectrogram_dir, species)

    if not os.path.exists(species_spectrogram_folder):
        print(f"Warning: Species spectrogram folder does not exist: {species_spectrogram_folder}. Skipping.")
        continue

    print(f"Loading enhanced spectrograms for {species} from {species_spectrogram_folder}...")
    image_files = glob.glob(os.path.join(species_spectrogram_folder, '*.png'))

    if not image_files:
        print(f"  No PNG files found in {species_spectrogram_folder}. Skipping.")
        continue

    for img_path in image_files:
        try:
            img = load_img(img_path, color_mode='grayscale', target_size=(IMG_HEIGHT, IMG_WIDTH))
            img_array = img_to_array(img)
            img_array = img_array / 255.0  # Normalizing to [0, 1]

            data_enhanced.append(img_array)
            labels_enhanced.append(species)
        except Exception as e:
            print(f"Error loading or processing {img_path}: {e}")

data_enhanced = np.array(data_enhanced)
labels_enhanced = np.array(labels_enhanced)

print(f"Loaded {len(data_enhanced)} enhanced spectrograms.")
print(f"Enhanced Data shape: {data_enhanced.shape}")
print(f"Enhanced Labels shape: {labels_enhanced.shape}")


# Re-encoding labels and spliting dataset for enhanced data
label_encoder_enhanced = LabelEncoder()
encoded_labels_enhanced = label_encoder_enhanced.fit_transform(labels_enhanced)

num_classes_enhanced = len(label_encoder_enhanced.classes_)
encoded_labels_onehot_enhanced = tf.keras.utils.to_categorical(encoded_labels_enhanced, num_classes=num_classes_enhanced)

print(f"Encoded enhanced labels (first 5): {encoded_labels_enhanced[:5]}")
print(f"One-hot encoded enhanced labels (first 5): {encoded_labels_onehot_enhanced[:5]}")
print(f"Classes: {label_encoder_enhanced.classes_}")

# Spliting the enhanced dataset into training and testing sets (80/20 split)
X_train_enhanced, X_test_enhanced, y_train_enhanced, y_test_enhanced = train_test_split(
    data_enhanced, encoded_labels_onehot_enhanced, test_size=0.2, random_state=42, stratify=encoded_labels_enhanced
)

print(f"X_train_enhanced shape: {X_train_enhanced.shape}")
print(f"y_train_enhanced shape: {y_train_enhanced.shape}")
print(f"X_test_enhanced shape: {X_test_enhanced.shape}")
print(f"y_test_enhanced shape: {y_test_enhanced.shape}")

"""neural networks are the portion of the code that change; everything before should stay same for each neural network change

FIRST ONE IS ORIGINAL CNN
"""

# importing essential functions from libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# actually defining the neural network and output layers so that a certain number of
# parameters are created
model_cnn_enhanced = Sequential([
    Conv2D(16, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 1)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(num_classes_enhanced, activation='softmax')
])

# Compiling the neural network using adam optimizer
model_cnn_enhanced.compile(optimizer='adam',
                           loss='categorical_crossentropy',
                           metrics=['accuracy'])

# Displaing a model summary to the user
model_cnn_enhanced.summary()

# now that the neural network model is created, the model is trained with the enhanced data
# 10 epochs and 4 batch sizes are consistent among the neural networks
history_cnn_enhanced = model_cnn_enhanced.fit(
    X_train_enhanced, y_train_enhanced,
    epochs=10,
    batch_size=4,
    validation_data=(X_test_enhanced, y_test_enhanced),
    verbose=1
)

# this is determing the test loss and accuracy for the the neural network
loss_enhanced, accuracy_enhanced = model_cnn_enhanced.evaluate(X_test_enhanced, y_test_enhanced, verbose=0)
print(f"Enhanced Test Loss: {loss_enhanced:.4f}")
print(f"Enhanced Test Accuracy: {accuracy_enhanced:.4f}")

# plotting the training history of the neural network to visualize both loss and accuracy
plt.figure(figsize=(12, 5))

# plotting the training loss graph
plt.subplot(1, 2, 1)
plt.plot(history_cnn_enhanced.history['loss'], label='Training Loss')
plt.plot(history_cnn_enhanced.history['val_loss'], label='Validation Loss')
plt.title('Loss over Epochs (Enhanced Data)')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

# plotting the training accuracy graph
plt.subplot(1, 2, 2)
plt.plot(history_cnn_enhanced.history['accuracy'], label='Training Accuracy')
plt.plot(history_cnn_enhanced.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy over Epochs (Enhanced Data)')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()


# in this section, we are taking random samples from the testing dataset to see how it
# predicts which species the sound is
import random
num_samples_to_show = 5
samples_to_display_indices = set()

# we wanted to see an incorrect prediction specifically
incorrect_indices = []
for idx in range(len(X_test_enhanced)):
    sample_spectrogram = X_test_enhanced[idx]
    true_label_onehot = y_test_enhanced[idx]
    sample_spectrogram_input = np.expand_dims(sample_spectrogram, axis=0)
    prediction_onehot = model_cnn_enhanced.predict(sample_spectrogram_input, verbose=0)[0]
    predicted_class_index = np.argmax(prediction_onehot)
    true_class_index = np.argmax(true_label_onehot)
    if true_class_index != predicted_class_index:
        incorrect_indices.append(idx)

if incorrect_indices and len(samples_to_display_indices) < num_samples_to_show:
    samples_to_display_indices.add(random.choice(incorrect_indices))

# we were also trying to get a 'barredowl' prediction specifically for presentation purposes
barredowl_class_index = -1
if 'barredowl' in label_encoder_enhanced.classes_:
    barredowl_class_index = label_encoder_enhanced.transform(['barredowl'])[0]

if barredowl_class_index != -1 and len(samples_to_display_indices) < num_samples_to_show:
    barredowl_indices = [idx for idx, label_onehot in enumerate(y_test_enhanced) if np.argmax(label_onehot) == barredowl_class_index]
    if barredowl_indices:

        eligible_barredowl_indices = list(set(barredowl_indices) - samples_to_display_indices)
        if eligible_barredowl_indices:
            samples_to_display_indices.add(random.choice(eligible_barredowl_indices))


# using other random samples, not necessarily incorrect or barred owl
all_test_indices = list(range(len(X_test_enhanced)))
while len(samples_to_display_indices) < num_samples_to_show and len(samples_to_display_indices) < len(all_test_indices):
    random_idx = random.choice(all_test_indices)
    if random_idx not in samples_to_display_indices:
        samples_to_display_indices.add(random_idx)

# converting set to list
final_display_indices = list(samples_to_display_indices)

# this next for loop is showing the predicted spectrogram/species for a few tests
# setting the figure size for displaying sample predictions
plt.figure(figsize=(15, len(final_display_indices) * 3))

for i, idx in enumerate(final_display_indices):
    sample_spectrogram = X_test_enhanced[idx]
    true_label_onehot = y_test_enhanced[idx]


    sample_spectrogram_input = np.expand_dims(sample_spectrogram, axis=0)

    # using the training to predict the species based on spectrogram model
    prediction_onehot = model_cnn_enhanced.predict(sample_spectrogram_input, verbose=0)[0]
    predicted_class_index = np.argmax(prediction_onehot)
    true_class_index = np.argmax(true_label_onehot)

    # converting indices back to bird species names for visualization purposes
    true_label_name = label_encoder_enhanced.inverse_transform([true_class_index])[0]
    predicted_label_name = label_encoder_enhanced.inverse_transform([predicted_class_index])[0]

    # showing user if the prediction was correct
    is_correct = (true_class_index == predicted_class_index)
    result_text = "Correct" if is_correct else f"Incorrect (True: {true_label_name})"
    color = "green" if is_correct else "red"

    # plotting the results to user
    plt.subplot(len(final_display_indices), 1, i + 1)
    plt.imshow(sample_spectrogram.squeeze(), cmap='viridis', origin='lower') # Use .squeeze() to remove the channel dimension for imshow
    plt.title(f"Prediction: {predicted_label_name} ({result_text})", color=color)
    plt.axis('off')

plt.tight_layout()
plt.show()

"""THIS ONE IS FOR THE SIMPLIFIED NEURAL NETWORK

Everything in these following code boxes are essentially the same code except that the numbers in the neural network definition were changed to create new output shapes and parameters. Therefore, the code was more lightly commented. For more thorough commenting of the same information the previous code block can be viewed.
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# actually defining new neural network model
model_cnn_ultra_simplified = Sequential([
    Conv2D(8, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 1)),
    MaxPooling2D((2, 2)),
    Conv2D(16, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(32, activation='relu'),
    Dropout(0.5),
    Dense(num_classes_enhanced, activation='softmax')
])

# compiling the model
model_cnn_ultra_simplified.compile(optimizer='adam',
                                   loss='categorical_crossentropy',
                                   metrics=['accuracy'])

# displaying model summary
print("\n--- Ultra Simplified CNN Model Summary ---")
model_cnn_ultra_simplified.summary()


# train the ultra-simplified model with the enhanced data
history_cnn_ultra_simplified = model_cnn_ultra_simplified.fit(
    X_train_enhanced, y_train_enhanced,
    epochs=10,
    batch_size=4,
    validation_data=(X_test_enhanced, y_test_enhanced),
    verbose=1
)


loss_ultra_simplified, accuracy_ultra_simplified = model_cnn_ultra_simplified.evaluate(X_test_enhanced, y_test_enhanced, verbose=0)
print(f"\nUltra-Simplified Test Loss: {loss_ultra_simplified:.4f}")
print(f"Ultra-Simplified Test Accuracy: {accuracy_ultra_simplified:.4f}")

# plotting training history
plt.figure(figsize=(12, 5))

# plot Loss specifically
plt.subplot(1, 2, 1)
plt.plot(history_cnn_ultra_simplified.history['loss'], label='Training Loss')
plt.plot(history_cnn_ultra_simplified.history['val_loss'], label='Validation Loss')
plt.title('Loss over Epochs (Ultra-Simplified CNN)')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

# plot accuracy specifically
plt.subplot(1, 2, 2)
plt.plot(history_cnn_ultra_simplified.history['accuracy'], label='Training Accuracy')
plt.plot(history_cnn_ultra_simplified.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy over Epochs (Ultra-Simplified CNN)')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()


# showing predictions from test set to user
import random
num_samples_to_show = 5
samples_to_display_indices_ultra = set()

# trying to get an incorrect prediction specifically
incorrect_indices_ultra = []
for idx in range(len(X_test_enhanced)):
    sample_spectrogram = X_test_enhanced[idx]
    true_label_onehot = y_test_enhanced[idx]
    sample_spectrogram_input = np.expand_dims(sample_spectrogram, axis=0)
    prediction_onehot = model_cnn_ultra_simplified.predict(sample_spectrogram_input, verbose=0)[0]
    predicted_class_index = np.argmax(prediction_onehot)
    true_class_index = np.argmax(true_label_onehot)
    if true_class_index != predicted_class_index:
        incorrect_indices_ultra.append(idx)

if incorrect_indices_ultra and len(samples_to_display_indices_ultra) < num_samples_to_show:
    samples_to_display_indices_ultra.add(random.choice(incorrect_indices_ultra))

# trying to get a 'barredowl' prediction specifically
barredowl_class_index_ultra = -1
if 'barredowl' in label_encoder_enhanced.classes_:
    barredowl_class_index_ultra = label_encoder_enhanced.transform(['barredowl'])[0]

if barredowl_class_index_ultra != -1 and len(samples_to_display_indices_ultra) < num_samples_to_show:
    barredowl_indices_ultra = [idx for idx, label_onehot in enumerate(y_test_enhanced) if np.argmax(label_onehot) == barredowl_class_index_ultra]
    if barredowl_indices_ultra:

        eligible_barredowl_indices_ultra = list(set(barredowl_indices_ultra) - samples_to_display_indices_ultra)
        if eligible_barredowl_indices_ultra:
            samples_to_display_indices_ultra.add(random.choice(eligible_barredowl_indices_ultra))


# using other random samples for testing predictions
all_test_indices = list(range(len(X_test_enhanced)))
while len(samples_to_display_indices_ultra) < num_samples_to_show and len(samples_to_display_indices_ultra) < len(all_test_indices):
    random_idx = random.choice(all_test_indices)
    if random_idx not in samples_to_display_indices_ultra:
        samples_to_display_indices_ultra.add(random_idx)

# converting set to list
final_display_indices_ultra = list(samples_to_display_indices_ultra)

# using for loop to display everything for each prediction sample
plt.figure(figsize=(15, len(final_display_indices_ultra) * 3))

for i, idx in enumerate(final_display_indices_ultra):
    sample_spectrogram = X_test_enhanced[idx]
    true_label_onehot = y_test_enhanced[idx]


    sample_spectrogram_input = np.expand_dims(sample_spectrogram, axis=0)

    # actually making the prediction
    prediction_onehot = model_cnn_ultra_simplified.predict(sample_spectrogram_input, verbose=0)[0]
    predicted_class_index = np.argmax(prediction_onehot)
    true_class_index = np.argmax(true_label_onehot)

    # converting indices back to names
    true_label_name = label_encoder_enhanced.inverse_transform([true_class_index])[0]
    predicted_label_name = label_encoder_enhanced.inverse_transform([predicted_class_index])[0]

    # showing user if the prediction was correct
    is_correct = (true_class_index == predicted_class_index)
    result_text = "Correct" if is_correct else f"Incorrect (True: {true_label_name})"
    color = "green" if is_correct else "red"
    # plotting predictions
    plt.subplot(len(final_display_indices_ultra), 1, i + 1)
    plt.imshow(sample_spectrogram.squeeze(), cmap='viridis', origin='lower')
    plt.title(f"Prediction: {predicted_label_name} ({result_text})", color=color)
    plt.axis('off')

plt.tight_layout()
plt.show()

"""NEW PARAMETERS FOR ORIGINAL CNN STRUCTURE"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# actually defining new neural network
model_cnn_enhanced = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 1)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(num_classes_enhanced, activation='softmax')
])

# compiling the model
model_cnn_enhanced.compile(optimizer='adam',
                           loss='categorical_crossentropy',
                           metrics=['accuracy'])

# displaying model summary for user
model_cnn_enhanced.summary()


# train the model with the enhanced data
history_cnn_enhanced = model_cnn_enhanced.fit(
    X_train_enhanced, y_train_enhanced,
    epochs=10,
    batch_size=4,
    validation_data=(X_test_enhanced, y_test_enhanced),
    verbose=1
)

# showing the test loss and accuracy
loss_enhanced, accuracy_enhanced = model_cnn_enhanced.evaluate(X_test_enhanced, y_test_enhanced, verbose=0)
print(f"Enhanced Test Loss: {loss_enhanced:.4f}")
print(f"Enhanced Test Accuracy: {accuracy_enhanced:.4f}")

# plotting training history
plt.figure(figsize=(12, 5))

# plotting loss specifically
plt.subplot(1, 2, 1)
plt.plot(history_cnn_enhanced.history['loss'], label='Training Loss')
plt.plot(history_cnn_enhanced.history['val_loss'], label='Validation Loss')
plt.title('Loss over Epochs (Enhanced Data)')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

# plotting accuracy specifically
plt.subplot(1, 2, 2)
plt.plot(history_cnn_enhanced.history['accuracy'], label='Training Accuracy')
plt.plot(history_cnn_enhanced.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy over Epochs (Enhanced Data)')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

# selecting random samples from testing portion to show users the prediction
import random
num_samples_to_show = 5
samples_to_display_indices = set()

# trying to get an incorrect prediction
incorrect_indices = []
for idx in range(len(X_test_enhanced)):
    sample_spectrogram = X_test_enhanced[idx]
    true_label_onehot = y_test_enhanced[idx]
    sample_spectrogram_input = np.expand_dims(sample_spectrogram, axis=0)
    prediction_onehot = model_cnn_enhanced.predict(sample_spectrogram_input, verbose=0)[0]
    predicted_class_index = np.argmax(prediction_onehot)
    true_class_index = np.argmax(true_label_onehot)
    if true_class_index != predicted_class_index:
        incorrect_indices.append(idx)

if incorrect_indices and len(samples_to_display_indices) < num_samples_to_show:
    samples_to_display_indices.add(random.choice(incorrect_indices))

# trying to get a 'barredowl' prediction
barredowl_class_index = -1
if 'barredowl' in label_encoder_enhanced.classes_:
    barredowl_class_index = label_encoder_enhanced.transform(['barredowl'])[0]

if barredowl_class_index != -1 and len(samples_to_display_indices) < num_samples_to_show:
    barredowl_indices = [idx for idx, label_onehot in enumerate(y_test_enhanced) if np.argmax(label_onehot) == barredowl_class_index]
    if barredowl_indices:

        eligible_barredowl_indices = list(set(barredowl_indices) - samples_to_display_indices)
        if eligible_barredowl_indices:
            samples_to_display_indices.add(random.choice(eligible_barredowl_indices))


# use other random samples
all_test_indices = list(range(len(X_test_enhanced)))
while len(samples_to_display_indices) < num_samples_to_show and len(samples_to_display_indices) < len(all_test_indices):
    random_idx = random.choice(all_test_indices)
    if random_idx not in samples_to_display_indices:
        samples_to_display_indices.add(random_idx)

# converting set to list
final_display_indices = list(samples_to_display_indices)

# showing model predictions
plt.figure(figsize=(15, len(final_display_indices) * 3))

for i, idx in enumerate(final_display_indices):
    sample_spectrogram = X_test_enhanced[idx]
    true_label_onehot = y_test_enhanced[idx]


    sample_spectrogram_input = np.expand_dims(sample_spectrogram, axis=0)

    # actual prediction of test set
    prediction_onehot = model_cnn_enhanced.predict(sample_spectrogram_input, verbose=0)[0]
    predicted_class_index = np.argmax(prediction_onehot)
    true_class_index = np.argmax(true_label_onehot)

    # converting indices back to names for display
    true_label_name = label_encoder_enhanced.inverse_transform([true_class_index])[0]
    predicted_label_name = label_encoder_enhanced.inverse_transform([predicted_class_index])[0]

    # showing the user if the prediction was correct
    is_correct = (true_class_index == predicted_class_index)
    result_text = "Correct" if is_correct else f"Incorrect (True: {true_label_name})"
    color = "green" if is_correct else "red"
    # plotting the prediction
    plt.subplot(len(final_display_indices), 1, i + 1)
    plt.imshow(sample_spectrogram.squeeze(), cmap='viridis', origin='lower') # Use .squeeze() to remove the channel dimension for imshow
    plt.title(f"Prediction: {predicted_label_name} ({result_text})", color=color)
    plt.axis('off')

plt.tight_layout()
plt.show()

"""CHANGING PARAMETERS FOR ULTRASIMPLIFIED MODEL"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# actually defining the new neural network
model_cnn_ultra_simplified = Sequential([
    Conv2D(16, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 1)),
    MaxPooling2D((2, 2)),
    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(num_classes_enhanced, activation='softmax')
])

# compiling the model
model_cnn_ultra_simplified.compile(optimizer='adam',
                                   loss='categorical_crossentropy',
                                   metrics=['accuracy'])

# displaying model summary for user
print("\n--- Ultra Simplified CNN Model Summary ---")
model_cnn_ultra_simplified.summary()

# training the ultra-simplified model with the enhanced data
history_cnn_ultra_simplified = model_cnn_ultra_simplified.fit(
    X_train_enhanced, y_train_enhanced,
    epochs=10,
    batch_size=4,
    validation_data=(X_test_enhanced, y_test_enhanced),
    verbose=1
)

# showing user the loss and accuracy of test set
loss_ultra_simplified, accuracy_ultra_simplified = model_cnn_ultra_simplified.evaluate(X_test_enhanced, y_test_enhanced, verbose=0)
print(f"\nUltra-Simplified Test Loss: {loss_ultra_simplified:.4f}")
print(f"Ultra-Simplified Test Accuracy: {accuracy_ultra_simplified:.4f}")

# plotting training history
plt.figure(figsize=(12, 5))

# plotting loss
plt.subplot(1, 2, 1)
plt.plot(history_cnn_ultra_simplified.history['loss'], label='Training Loss')
plt.plot(history_cnn_ultra_simplified.history['val_loss'], label='Validation Loss')
plt.title('Loss over Epochs (Ultra-Simplified CNN)')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

# plotting accuracy
plt.subplot(1, 2, 2)
plt.plot(history_cnn_ultra_simplified.history['accuracy'], label='Training Accuracy')
plt.plot(history_cnn_ultra_simplified.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy over Epochs (Ultra-Simplified CNN)')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

# choosing random samples from test data to show user how the prediction works
import random
num_samples_to_show = 5
samples_to_display_indices_ultra = set()

# trying to get an incorrect prediction
incorrect_indices_ultra = []
for idx in range(len(X_test_enhanced)):
    sample_spectrogram = X_test_enhanced[idx]
    true_label_onehot = y_test_enhanced[idx]
    sample_spectrogram_input = np.expand_dims(sample_spectrogram, axis=0)
    prediction_onehot = model_cnn_ultra_simplified.predict(sample_spectrogram_input, verbose=0)[0]
    predicted_class_index = np.argmax(prediction_onehot)
    true_class_index = np.argmax(true_label_onehot)
    if true_class_index != predicted_class_index:
        incorrect_indices_ultra.append(idx)

if incorrect_indices_ultra and len(samples_to_display_indices_ultra) < num_samples_to_show:
    samples_to_display_indices_ultra.add(random.choice(incorrect_indices_ultra))

# trying to get a 'barredowl' prediction
barredowl_class_index_ultra = -1
if 'barredowl' in label_encoder_enhanced.classes_:
    barredowl_class_index_ultra = label_encoder_enhanced.transform(['barredowl'])[0]

if barredowl_class_index_ultra != -1 and len(samples_to_display_indices_ultra) < num_samples_to_show:
    barredowl_indices_ultra = [idx for idx, label_onehot in enumerate(y_test_enhanced) if np.argmax(label_onehot) == barredowl_class_index_ultra]
    if barredowl_indices_ultra:

        eligible_barredowl_indices_ultra = list(set(barredowl_indices_ultra) - samples_to_display_indices_ultra)
        if eligible_barredowl_indices_ultra:
            samples_to_display_indices_ultra.add(random.choice(eligible_barredowl_indices_ultra))


# using other random samples
all_test_indices = list(range(len(X_test_enhanced)))
while len(samples_to_display_indices_ultra) < num_samples_to_show and len(samples_to_display_indices_ultra) < len(all_test_indices):
    random_idx = random.choice(all_test_indices)
    if random_idx not in samples_to_display_indices_ultra:
        samples_to_display_indices_ultra.add(random_idx)

# converting set to list
final_display_indices_ultra = list(samples_to_display_indices_ultra)

# plotting the prediction results
plt.figure(figsize=(15, len(final_display_indices_ultra) * 3))

for i, idx in enumerate(final_display_indices_ultra):
    sample_spectrogram = X_test_enhanced[idx]
    true_label_onehot = y_test_enhanced[idx]


    sample_spectrogram_input = np.expand_dims(sample_spectrogram, axis=0)

    # predicting the species based on spectrogram
    prediction_onehot = model_cnn_ultra_simplified.predict(sample_spectrogram_input, verbose=0)[0]
    predicted_class_index = np.argmax(prediction_onehot)
    true_class_index = np.argmax(true_label_onehot)

    # converting indices back to names for easier visualization
    true_label_name = label_encoder_enhanced.inverse_transform([true_class_index])[0]
    predicted_label_name = label_encoder_enhanced.inverse_transform([predicted_class_index])[0]

    # showing user if the prediction was correct
    is_correct = (true_class_index == predicted_class_index)
    result_text = "Correct" if is_correct else f"Incorrect (True: {true_label_name})"
    color = "green" if is_correct else "red"
    # plotting prediction results
    plt.subplot(len(final_display_indices_ultra), 1, i + 1)
    plt.imshow(sample_spectrogram.squeeze(), cmap='viridis', origin='lower') # Use .squeeze() to remove the channel dimension for imshow
    plt.title(f"Prediction: {predicted_label_name} ({result_text})", color=color)
    plt.axis('off')

plt.tight_layout()
plt.show()